name: Build Windows EXE

on:
  push:
    branches:
      - main  # 或者你用的分支名，如 main_name_replace2.1_win

jobs:
  build-exe:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build executable with icon
      run: |
        pyinstaller --noconfirm --windowed --onefile --icon=icon.ico medical_data_tool.py

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: medical_data_tool_exe
        path: dist/medical_data_tool.exe
